docs_dir: API documentation
nav:
- Home: README.md
- Database management: database-management.md
- eduVid: eduvid.md
repo_url: https://github.com/Programmierpraktikum-MVA/big-brother
site_name: big-brother
theme: readthedocs
